version: "3.9"
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./backend/app/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env

  input:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./backend/app:/app
      - ./data:/app/data
    working_dir: /app/db
    command: ["python", "input_to_database.py"]